name: CI Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  app-tests:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - name: Get the latest code
      uses: actions/checkout@v2.3.2
    - name: Copy .env
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./
    - name: Install Dependencies
      run: |
        composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      working-directory: ./
    - name: Generate key
      run: |
        php artisan key:generate
      working-directory: ./
    - name: Directory Permissions
      run: |
        chmod -R 777 storage bootstrap/cache
      working-directory: ./
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
      run: |
        php artisan migrate
        php artisan test
  validate-code:
    name: Code style validation and code static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: phpunit-bridge
          extensions: pdo, pdo_sqlite, sqlite3, pcntl, intl, zip, bcmath, pcov
          coverage: pcov

      - name: Validate composer
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader

      - name: Run Pint To Validate Code Style
        run: composer pint-test

